### ISSUE TITLE
Master todo

### ISSUE THREAD

**Issue by dinesh24murali** [dinesh24murali/mongodb_learn#1]
These are things that I need to research on MongoDB

- [x] Indexing
- [x] Combining two collections using Aggregation pipelines
- [x] Joins
- [ ] DB backup and restore
- [ ] Sharding
- [ ] UpdateMany with condition
- [ ] Store files in DB
- [ ] Research on BSON
